SecureShare/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from master import views as master

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
    url(r'^reports/', include('reports.urls', namespace="reports")),
    url(r'^$', include('master.urls', namespace="master")),
    url(r'^messages/', include('post.urls', namespace="messages")),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^tinymce/', include('tinymce.urls')),
]

master/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),

]

post/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^new/$', views.new, name='new'),
    url(r'^inbox/$', views.inbox, name='inbox'),
    url(r'^(?P<message_id>[0-9]+)/delete/$', views.delete, name='delete'),
    url(r'^(?P<message_id>[0-9]+)/read/$', views.read, name='read'),
]

reports/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^reports/$', views.reports, name='reports'),
    url(r'^folders/$', views.folders, name='folders'),
    url(r'^search_reports/$', views.search, name = 'search'),
    url(r'^attachments/$', views.attachments, name='attachments'),
    url(r'^(?P<report_id>[0-9]+)/contributors/$', views.contributors, name='contributors'),
    url(r'^public/$', views.public, name='public'),
    url(r'^(?P<report_id>[0-9]+)/edit_report/$', views.edit_report, name='edit_report'),
    url(r'^(?P<report_id>[0-9]+)/delete_report/$', views.delete_report, name='delete_report'),
    url(r'^(?P<folder_id>[0-9]+)/edit_folder/$', views.edit_folder, name='edit_folder'),
    url(r'^move/$', views.move, name='move'),
    url(r'^(?P<report_id>[0-9]+)/attachments/$', views.attachments, name='attachments'),
    url(r'^(?P<report_id>[0-9]+)/read_report/$', views.read_report, name='read_report'),
    url(r'^(?P<attachment_id>[0-9]+)/delete_attachment/$', views.delete_attachment, name='delete_attachment'),
    url(r'^api_available_reports/$', views.api_available_reports, name='api_available_reports'),
    url(r'^api_public_reports/$', views.api_public_reports, name='api_public_reports'),
    url(r'^(?P<attachment_id>[0-9]+)/download_attachment/$', views.api_download_attachment, name='api_download_attachment'),
    url(r'^api_add_report/$', views.api_add_report, name='api_add_report'),

]

reports/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import os

class Report(models.Model):
    title = models.CharField(max_length=30)
    description = models.CharField(max_length = 200)
    create_date = models.DateTimeField('date created')
    public = models.BooleanField(default=True)
    creator = models.ForeignKey(User)
    #encrypted = models.BooleanField(default=False)
    def get_creator(self):
        return str(self.creator)
    def is_public(self):
        return self.public

class Folder(models.Model):
    label = models.CharField(max_length=30)
    reports = models.ManyToManyField(Report)
    owner = models.ForeignKey(User)
    def __str__(self):
        return self.label

def get_upload_file_name(instance,filename):
    return "uploaded_files/%s_%s" % (str(timezone.now()).replace('.','_'),filename)

class Attachment (models.Model):
    name = models.CharField(max_length=30)
    upload = models.FileField(upload_to=get_upload_file_name)
    key = models.CharField(max_length=100)
    encrypted = models.BooleanField(default=False)
    upload_date = models.DateTimeField('date uploaded', auto_now_add=True)
    report = models.ForeignKey(Report)
    def __str__(self):
        return self.name
    def filename(self):
        return os.path.basename(self.upload.path)
    def has_access(self, user):
        retval = False
        try:
            for folder in user.folder_set.all():
                for report in folder.reports.all():
                    if self in report.attachment_set.all():
                        retval = True
            if self.report.public == True:
                retval = True
        except:
            pass
        return retval

class Contributor (models.Model):
    name = models.CharField(max_length=30)
    def __str__(self):
        return self.name

reports/forms.py
from django import forms
from .models import Report, Folder, Attachment, Contributor

class ReportForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control'}))
    public = forms.BooleanField(required=False)
    class Meta:
        model = Report
        fields = ('title', 'description', 'public')

class AttachmentForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    upload = forms.FileField()
    class Meta:
        model = Attachment
        fields = ('name', 'upload')

class ContributorForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    class Meta:
        model = Contributor
        fields = ('name',)

reports/views.py
from django.utils import timezone
from django.shortcuts import render, render_to_response
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import messages
from .forms import ReportForm, AttachmentForm
import re
from django.db.models import Q
from django.template import RequestContext
from .models import Report, Folder, Attachment
from django.contrib.auth.models import Group, User
from Crypto.Hash import MD5
from Crypto.Cipher import DES
from Crypto.Hash import SHA256
from django.core.mail import send_mail

@login_required
def reports(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        f = ReportForm(request.POST)
        # check whether it's valid:
        if f.is_valid():
            # Save the form data to the database.
            # But dont yet commit, we still have some data to add.
            report = f.save(commit=False)
            report.create_date = timezone.now()
            report.creator = request.user
            # NOW we can save
            report.save();

            folder = request.user.folder_set.get(label="Uncategorized")
            folder.reports.add(report)
            folder.save()

            # redirect to a new URL:
            messages.success(request, 'Report Created.')
            return HttpResponseRedirect('/')
        else:
            messages.warning(request, 'Report Not Created!')
            return render(request, 'reports/reports.html', {'report_form': f})
    # if a GET (or any other method) we'll create a blank form
    else:
        report_form = ReportForm()
        return render(request, 'reports/reports.html', {'report_form': report_form})

    return render(request, 'reports/reports.html')

@login_required
def folders(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        if not Folder.objects.filter(owner=request.user, label=request.POST['folder_name']):
            newfolder = Folder()
            newfolder.label= request.POST['folder_name']
            newfolder.owner = request.user
            newfolder.save()
            messages.success(request, 'Folder Created!')
            return HttpResponseRedirect('/')
        else:
           messages.warning(request, 'You already have a folder with that name!')
           return HttpResponseRedirect('/')
    else:
        return HttpResponseRedirect('/')

@login_required
def attachments(request, report_id):
    if request.method == "POST":
        report = Report.objects.get(id=report_id)
        f = AttachmentForm(request.POST, request.FILES)
        # check whether it's valid:
        print('upload' in request.FILES)
        if f.is_valid():
            # Save the form data to the database.
            # But dont yet commit, we still have some data to add.
            attachment = f.save(commit=False)
            attachment.upload_date = timezone.now()
            attachment.report = report
            # NOW we can save
            attachment.save();

            h = MD5.new()
            chunk_size = 8192
            with open(attachment.upload.path, 'rb') as f:
                while True:
                    chunk = f.read(chunk_size)
                    if len(chunk) == 0:
                        break
                    h.update(chunk)
            attachment.key = h.hexdigest()
            attachment.save()

            messages.success(request, 'Attachment added!')
            return render(request, 'reports/read_report.html', {'report': report, "attachment_form": AttachmentForm()})
        else:
            messages.warning(request, 'Attachment failed to add!')
            return render(request, 'reports/read_report.html', {'report': report, "attachment_form": f})

@login_required
def delete_report(request, report_id):
    if Report.objects.filter(creator=request.user) or request.user.is_superuser:
        Report.objects.get(id=report_id).delete()
        messages.success(request, 'Report destroyed')
        if request.user.is_superuser:
            return HttpResponseRedirect('/accounts/sitemanager/')
        else:
            return HttpResponseRedirect('/')
    else:
        messages.warning(request, "Your report was not deleted.")
        if request.user.is_superuser:
            return HttpResponseRedirect('/accounts/sitemanager/')
        else:
            return HttpResponseRedirect('/')

@login_required
def edit_report(request, report_id):
    report = Report.objects.get(id=report_id)
    if request.method == 'POST':
        form = ReportForm(request.POST, instance=report)
        if form.is_valid():
            report = form.save(commit=True)
            messages.success(request, 'Report Edited.')
            return HttpResponseRedirect('/')
        else:
            form = ReportForm(instance=report)
            messages.warning(request, 'Report Not Edited!')
            #return HttpResponseRedirect('/')
    else:
        form = ReportForm(instance=report)

    return render(request, 'reports/edit_report.html', {'report_form': form,'report_id':report_id})

@login_required
def edit_folder(request, folder_id):
    if request.method == 'POST': #rename folder
        if not Folder.objects.filter(owner=request.user, label=request.POST['folder_name']):
            Folder.objects.filter(pk=folder_id).update(label=request.POST['folder_name'])
            messages.success(request, 'Folder Renamed!')
            return HttpResponseRedirect('/')
        else:
           messages.warning(request, 'You already have a folder with that name!')
           return render(request, 'reports/rename_folder.html')
    if(request.GET.get('dlt')): #button pressed, delete folder
        if Folder.objects.filter(owner=request.user):
            Folder.objects.get(id=folder_id).delete()
            messages.success(request, 'Folder destroyed')
            return HttpResponseRedirect('/')
        else:
            messages.warning(request, "Your folder is still among us.")
            return HttpResponseRedirect('/')
    f = Folder.objects.get(pk=folder_id)
    return render(request, 'reports/rename_folder.html', {'folder_id':folder_id, 'labeled':f.label})

@login_required
def move(request):
    if request.method == 'POST':

        rep = Report.objects.get(id = request.POST['currep'])

        try:
            Folder.objects.get(id = request.POST['move_to']).reports.add(rep)
            Folder.objects.get(id = request.POST['move_from']).reports.remove(rep)
            messages.success(request, 'Folder successfully moved!')
        except:
            Folder.objects.get(id = request.POST['move_to']).reports.add(rep)
            messages.success(request, "here i am")

            # f = rep.folder_set.all()
            # move_from = f.filter(owner = request.user)
            # Folder.objects.get(id = request.POST['move_to']).reports.add(rep)
            # move_from.reports.remove(rep)
            # messages.success(request, 'Folder successfully moved!')
        return HttpResponseRedirect('/')


@login_required
def read_report(request, report_id):
    if request.method == "POST":
        report = Report.objects.get(id=report_id)
        f = AttachmentForm(request.POST, request.FILES)
        # check whether it's valid:
        # print('upload' in request.FILES)
        # if f.is_valid():
        #     # Save the form data to the database.
        #     # But dont yet commit, we still have some data to add.
        #     attachment = f.save(commit=False)
        #     attachment.upload_date = timezone.now()
        #     attachment.report = report
        #     # NOW we can save
        #     attachment.save();
        #     messages.success(request, 'Attachment added!')
        #     return render(request, 'reports/read_report.html', {'report': report, "attachment_form": AttachmentForm()})
        # else:
        #     messages.warning(request, 'Attachment failed to add!')
        #     return render(request, 'reports/read_report.html', {'report': report, "attachment_form": f})
    else:
        report = Report.objects.get(id=report_id)
        if Report.objects.filter(creator=request.user) or report.is_public():
            report.save()
            attachment_form = AttachmentForm()
            return render(request, 'reports/read_report.html', {'report': report, "attachment_form": attachment_form})
        else:
            messages.warning(request, "Couldn't read your report")
            return HttpResponseRedirect('/')

@login_required
def delete_attachment(request, attachment_id):
    try:
        attachment = Attachment.objects.get(id=attachment_id)
        os.remove(attachment.upload.path)
        report = attachment.report
        attachment.delete()
        messages.success(request, "Attachment Deleted")
        return render(request, 'reports/read_report.html', {'report': report, "attachment_form": AttachmentForm()})
    except:
        messages.warning(request, "ERROR: Attachment Not Deleted!")
        return HttpResponseRedirect(request.META.get('HTTP_REFERER','/'))

@login_required
def search(request):
    query_string = ''
    found_entries = None
    found_entries_two = None
    if ('q' in request.GET) and request.GET['q'].strip():
        query_string = request.GET['q']
        entry_query = get_query(query_string,  ['title', 'description',])
        found_entries = Report.objects.filter(entry_query)
        query_string = request.GET['q']

        if "AND" in query_string:
            query_string = request.GET['q'].replace('AND','')

        entry_query = get_query(query_string, ['title', 'description', ])
        all_entries = Report.objects.filter(entry_query)

        if "OR" in query_string:
            query_string = request.GET['q'].split('OR')
            query_string_one = query_string[0]

reports/templates/reports/edit_report.html
{% extends "master/base.html" %}
{% block body_block %}

<h3>Edit report</h3>
<form method="post" action="/reports/{{ report_id }}/edit_report/">
    {% csrf_token %}

    {% for field in report_form.visible_fields %}
    <div class="form-group">
      {{ field.errors }}
      <label>{{ field.label }}</label>
      {{ field }}
    </div>
    {% endfor %}
    <br/>
  <button type="submit" class="btn btn-default">Edit Report</button>
</form>

{% endblock %}

reports/templates/reports/public.html
{% extends "master/base.html" %}
{% block body_block %}
<div class="panel panel-default">
  <div class="panel-heading">
      Public Reports
  </div>
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Date Created</th>
      </tr>
      {% for report in reports %}
      <tr>
        <td><a href="{% url 'reports:read_report' report.id %}">{{ report.title }}</a></td>
        <td>{{ report.create_date }}</td>
      </tr>
      {% endfor %}
    </table>
</div>
{% endblock %}

reports/templates/reports/read_report.html
{% extends "master/base.html" %}
{% block body_block %}

    {% for folder in user.folder_set.all %}
        {% if forloop.counter == 1 %}
            {% if report not in folder.reports.all and user.username != report.get_creator %}
                <h4><p class="text-danger">This report was not shared with you.</p></h4>

                {% if request.user.is_superuser and user.username != report.get_creator %}
                    <h4><p class="text-success">You can see this report because you're a site manager.</p></h4>
                {% endif %}
                {% if report.is_public and user.username != report.get_creator %}
                    <h4><p class="text-success">You can see this report because it's public.</p></h4>
                {% endif %}
            {% endif %}

        {% endif %}
    {% endfor %}



    {% for folder in user.folder_set.all %}
        {% if report in folder.reports.all or request.user.is_superuser or report.is_public %}

            <div class="well">
                <a class="btn btn-default" href="{% url 'master:index' %}">Back to List of Reports</a>
                <a class="btn btn-primary" href="{% url 'reports:reports' %}">New Report</a>
                {% if user.username == report.get_creator or request.user.is_superuser %}
                    <a class="btn btn-info" href="{% url "reports:edit_report" report.id %}">Edit</a>
                    <a class="btn btn-danger" href="{% url "reports:delete_report" report.id %}">Delete</a>
                {% endif %}
            </div>

            <div class="page-header">
                <h1>{{ report.title }}
                    <small>Created by {{ report.creator }} <span
                            class="label label-default">{{ report.create_date }}</span></small>
                </h1>
            </div>
            <h4>Public: {{ report.public }}</h4> <Br>
            <h4>Description:</h4> {{ report.description }}

            <br> <br>
            <div class="panel panel-default">
                <div class="panel-heading">Attachments</div>
                <ul class="list-attachments">
                    <table class="table">
                        <tr>
                            <th>File Name</th>
                            <th>Encrypted</th>
                            <th>Checksum</th>
                            <th>Upload Date</th>
                            <th>Actions</th>
                        </tr>
                        {% for attachment in report.attachment_set.all %}
                            <tr>
                                <td>{{ attachment.name }}</td>
                                <td>{{ attachment.encrypted }}</td>
                                <td>{{ attachment.key }}</td>
                                <td>{{ attachment.upload_date }}</td>
                                <td>{% if user.username == report.get_creator or request.user.is_superuser %}<a href="{% url 'reports:delete_attachment' attachment.id %}">Delete</a>{% endif %} {% if not attachment.encrypted %}| <a href="{% url 'reports:api_download_attachment' attachment.id %}">Download</a>{% endif %}</td>
                            </tr>
                        {% endfor %}
                    </table>
                </ul>
            </div>

            <h3>Add New Unencrypted Attachment</h3>
            <form class="form-inline" method="post" enctype="multipart/form-data"
                  action="{% url 'reports:attachments' report.id %}">
                {% csrf_token %}

                {% for field in attachment_form.visible_fields %}
                    <div class="form-group">
                        {{ field.errors }}
                        <label>{{ field.label }}</label>
                        {{ field }}
                    </div>
                {% endfor %}
                <button type="submit" class="btn btn-default">Upload Attachment</button>
            </form>

            {% if user.username == report.get_creator or request.user.is_superuser %}
                <br> <br>

                <h3>Add contributors to the report</h3>
                <form class="form-inline" method="post" action="{% url 'reports:contributors' report.id %}">
                    <div class="form-group">
                        {% csrf_token %}
                        <select name="group_name" class="form-control">
                            {% for group in user.groups.all %}
                                <option value="{{ group.name }}">{{ group.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <button type="submit" class="btn btn-default">Add Group as Contributor</button>
                </form>
            {% endif %}

            {{ "<!--" }}
        {% endif %}
    {% endfor %}
    {{ "-->" }}

{% endblock %}

reports/templates/reports/rename_folder.html
{% extends "master/base.html" %}
{% block body_block %}
    <h2> Folder: {{labeled}}</h2>

<div class="row">
  <div class="col-md-6">
    <div class="well">
      <form class="form-inline" method="post">
        <div class="form-group">
          {% csrf_token %}
          <input type="text" name="folder_name" class="form-control" placeholder="New Folder Name">
        </div>
        <button type="submit" class="btn btn-default" >Rename Folder</button>
      </form>
    </div>
  </div>
    <div class="col-md-6">
        <div class="well">
            <form method="get">
                <input type="submit" class="btn btn-default" value="Delete Folder" name="dlt">
            </form>
        </div>
    </div>
</div>
{% endblock %}

reports/templates/reports/reports.html
{% extends "master/base.html" %}
{% block body_block %}

<h3>Create new report</h3>
<form method="post" action="/reports/reports/">
    {% csrf_token %}

    {% for field in report_form.visible_fields %}
    <div class="form-group">
      {{ field.errors }}
      <label>{{ field.label }}</label>
      {{ field }}
    </div>
    {% endfor %}

    <br/>
  <button type="submit" class="btn btn-default">Create New Report</button>
</form>

{% endblock %}

reports/templates/reports/search_results.html
{% extends "master/base.html" %}
{% block body_block %}

<div class="well">
    <form class="form-inline" method="get" action="/reports/search_reports">
        <input type="text" class="form-control" name="q" size="90" id="id_q" size="45" placeholder="Enter Search Keywords"/>
        <input type="submit" class="btn btn-default" class="form-control" value="Search"/>
    </form>
</div>

    {% if found_entries %}
        <div class="panel panel-default">
            <table class="table">
                <tr>
                    <th>Name</th>
                    <th>Public</th>
                    <th>Date Created</th>
                    <th>Actions</th>
                    <th>Move to...</th>
                </tr>
                {% for report in found_entries %}
                    <tr>
                        <td><a href="{% url 'reports:read_report' report.id %}">{{ report.title }}</a></td>
                        <td>{{ report.public }}</td>
                        <td>{{ report.create_date }}</td>
                        <td><a href="{% url "reports:edit_report" report.id %}">Edit</a> &nbsp; &nbsp;
                        <a href="{% url "reports:delete_report" report.id %}">Delete</a></td>
                        <td>
                            <form id="folder_move_form" method="post" action="/reports/move/">
                                {% csrf_token %}
                                <select name="move_to" onChange="$('#folder_move_form').submit()">
                                    <option value="" disabled="disabled" selected="selected">Please select a folder
                                    </option>
                                    {% for listfold in user.folder_set.all %}
                                        {% if listfold.label != "Shared With Me" %}
                                            <option value="{{ listfold.id }}"> {{ listfold.label }}</option>
                                        {% endif %}
                                    {% endfor %}
                                </select>
                                <input type="hidden" name="move_from" value="{{ folder.id }}">
                                <input type="hidden" name="currep" value="{{ report.id }}">
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    {% else %}
    <h3> No entries were found. </h3>
    {% endif %}

{% endblock %}