SecureShare/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from master import views as master

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
    url(r'^reports/', include('reports.urls', namespace="reports")),
    url(r'^$', include('master.urls', namespace="master")),
    url(r'^messages/', include('post.urls', namespace="messages")),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^tinymce/', include('tinymce.urls')),
]

accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^groups/$', views.groups, name='groups'),
    url(r'^sitemanager/$', views.sitemanager, name='sitemanager'),
    url(r'^(?P<user_id>[0-9]+)/user_view/$', views.user_view, name='user_view'),
    url(r'^(?P<user_id>[0-9]+)/deactivate/$', views.deactivate, name='deactivate'),
    url(r'^(?P<user_id>[0-9]+)/activate/$', views.activate, name='activate'),
    url(r'^(?P<user_id>[0-9]+)/makeSiteManager/$', views.makeSiteManager, name='makeSiteManager'),
    url(r'^(?P<user_id>[0-9]+)/unmakeSiteManager/$', views.unmakeSiteManager, name='unmakeSiteManager'),
    url(r'^groups/sitemanager/$', views.groupsSM, name='groupsSM'),
]

master/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),

]

post/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^new/$', views.new, name='new'),
    url(r'^inbox/$', views.inbox, name='inbox'),
    url(r'^(?P<message_id>[0-9]+)/delete/$', views.delete, name='delete'),
    url(r'^(?P<message_id>[0-9]+)/read/$', views.read, name='read'),
]

reports/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^reports/$', views.reports, name='reports'),
    url(r'^folders/$', views.folders, name='folders'),
    url(r'^search_reports/$', views.search, name = 'search'),
    url(r'^attachments/$', views.attachments, name='attachments'),
    url(r'^(?P<report_id>[0-9]+)/contributors/$', views.contributors, name='contributors'),
    url(r'^public/$', views.public, name='public'),
    url(r'^(?P<report_id>[0-9]+)/edit_report/$', views.edit_report, name='edit_report'),
    url(r'^(?P<report_id>[0-9]+)/delete_report/$', views.delete_report, name='delete_report'),
    url(r'^(?P<folder_id>[0-9]+)/edit_folder/$', views.edit_folder, name='edit_folder'),
    url(r'^move/$', views.move, name='move'),
    url(r'^(?P<report_id>[0-9]+)/attachments/$', views.attachments, name='attachments'),
    url(r'^(?P<report_id>[0-9]+)/read_report/$', views.read_report, name='read_report'),
    url(r'^(?P<attachment_id>[0-9]+)/delete_attachment/$', views.delete_attachment, name='delete_attachment'),
    url(r'^api_available_reports/$', views.api_available_reports, name='api_available_reports'),
    url(r'^api_public_reports/$', views.api_public_reports, name='api_public_reports'),
    url(r'^(?P<attachment_id>[0-9]+)/download_attachment/$', views.api_download_attachment, name='api_download_attachment'),
    url(r'^api_add_report/$', views.api_add_report, name='api_add_report'),

]

accounts/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import User

class Security(models.Model):
    user = models.OneToOneField(User)
    pem_key = models.CharField(max_length=1000, default="key")
    public_key = models.CharField(max_length=1000, default="key")

def get_unread(self):
    return self.recipient.filter(unread=True).count()

User.add_to_class('get_unread', get_unread)

#public_key = models.CharField(max_length=1000, default="key")
#public_key.contribute_to_class(User, 'public_key')

#pem_key = models.CharField(max_length=1000, default="key")
#pem_key.contribute_to_class(User, 'pem_key')

accounts/forms.py
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'class':'form-control'}))
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password')

accounts/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from .forms import UserForm
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.contrib.auth.models import Group, User
from .models import Security
from reports.models import Folder, Report
from Crypto import Random
import random
import string
from Crypto.PublicKey import RSA
from django.core.mail import EmailMessage



# Create your views here.

def register(request):

    # A boolean value for telling the template whether the registration was successful.
    # Set to False initially. Code changes value to True when registration succeeds.
    registered = False

    # If it's a HTTP POST, we're interested in processing form data.
    if request.method == 'POST':
        # Attempt to grab information from the raw form information.
        # Note that we make use of both UserForm and UserProfileForm.
        user_form = UserForm(data=request.POST)

        # If the two forms are valid...
        if user_form.is_valid():
            # Save the user's form data to the database.
            user = user_form.save()

            # Now we hash the password with the set_password method.
            # Once hashed, we can update the user object.
            user.set_password(user.password)
            default_folder = Folder()
            default_folder.label = "Uncategorized"
            default_folder.owner = user
            default_folder.save()
            user.folder_set.add(default_folder)
            shared_folder = Folder()
            shared_folder.label = "Shared With Me"
            shared_folder.owner = user
            shared_folder.save()
            user.folder_set.add(shared_folder)

            # Keys for post app
            random_generator = Random.new().read
            key = RSA.generate(1024, random_generator)
            key_security = Security()
            key_security.pem_key = ''.join([random.choice(string.ascii_letters + string.digits) for n in range(32)])
            key_security.public_key = key.publickey().exportKey('PEM', "password")
            email = EmailMessage('[SecureShare] Welcome to SecureShare!', 'Welcome to SecureShare '+user.first_name+'! Please save the attached PEM file in a safe place. You will need this to unencrypt any encrypted messages you receive.',
            'secureshare21uvaaaay@yahoo.com',
            [user.email])
            email.attach('privatekey.pem', key.exportKey('PEM', key_security.pem_key), 'application/x-pem-file')
            email.send()

            user.save()

            key_security.user = user
            key_security.save()

            # Update our variable to tell the template registration was successful.
            registered = True

        # Invalid form or forms - mistakes or something else?
        # Print problems to the terminal.
        # They'll also be shown to the user.
        else:
            print(user_form.errors)

    # Not a HTTP POST, so we render our form using two ModelForm instances.
    # These forms will be blank, ready for user input.
    else:
        user_form = UserForm()

    # Render the template depending on the context.
    return render(request, 'accounts/register.html', {'user_form': user_form, 'registered': registered} )

def user_login(request):

    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
        # Gather the username and password provided by the user.
        # This information is obtained from the login form.
                # We use request.POST.get('<variable>') as opposed to request.POST['<variable>'],
                # because the request.POST.get('<variable>') returns None, if the value does not exist,
                # while the request.POST['<variable>'] will raise key error exception
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Use Django's machinery to attempt to see if the username/password
        # combination is valid - a User object is returned if it is.
        user = authenticate(username=username, password=password)

        # If we have a User object, the details are correct.
        # If None (Python's way of representing the absence of a value), no user
        # with matching credentials was found.
        if user:
            # Is the account active? It could have been disabled.
            if user.is_active:
                # If the account is valid and active, we can log the user in.
                # We'll send the user back to the homepage.
                login(request, user)
                return HttpResponseRedirect('/')
            else:
                # An inactive account was used - no logging in!
                messages.warning(request, 'Your account is disabled. Please contact support.')
                return HttpResponseRedirect('/')
        else:
            # Bad login details were provided. So we can't log the user in.
            # TODO: USE FLASH MESSAGES -----------------
            messages.warning(request, 'Invalid Login.')
            return HttpResponseRedirect(reverse('accounts:login'))

    # The request is not a HTTP POST, so display the login form.
    # This scenario would most likely be a HTTP GET.
    else:
        # No context variables to pass to the template system, hence the
        # blank dictionary object...
        return render(request, 'accounts/login.html', {})


# Use the login_required() decorator to ensure only those logged in can access the view.
@login_required
def user_logout(request):
    # Since we know the user is logged in, we can now just log them out.
    logout(request)
    messages.success(request, 'You are now logged out.')
    return HttpResponseRedirect('/')

@login_required
def groups(request):
    if request.method == 'POST':
        if request.POST.get('user_name'):
            user_name = request.POST.get('user_name')
            group_name = request.POST.get('group_name')
            try:
                user = User.objects.get(username=user_name)
                group = Group.objects.get(name=group_name)
                user.groups.add(group)
                user.save()
                full_name = user.first_name + " " + user.last_name
                messages.success(request, full_name + " added to group!")
            except:
                messages.warning(request, 'User not added to group: Username not Found!')
        else:
            group_name = request.POST.get('group_name')
            try:
                newgroup = Group()
                newgroup.name = group_name
                newgroup.save()
                request.user.groups.add(newgroup)
                request.user.save()
                messages.success(request, 'Group Created.')
            except:
                messages.warning(request, 'Group Creation Failed. Group Already Exists.')

        return HttpResponseRedirect('/accounts/groups')
    return render(request, 'accounts/groups.html', {})


@user_passes_test(lambda u: u.is_superuser)
def sitemanager(request):
    return render(request, 'accounts/sitemanager.html', {'all_users':User.objects.all(), 'all_groups': Group.objects.all()})

@user_passes_test(lambda u: u.is_superuser)
def user_view(request, user_id):
    member = User.objects.get(id=user_id)
    if request.method == "POST":
            #something about editing the user?
        return render(request, 'accounts/sitemanager.html', {'all_users':User.objects.all()})
    else:
        return render(request, 'accounts/user_view.html', {'member':member})

@user_passes_test(lambda u: u.is_superuser)
def deactivate(request, user_id):
    member = User.objects.get(id=user_id)
    try:
        member.is_active=False
        member.save()
        messages.success(request, member.username + "'s account deactivated")
    except:
        messages.warning(request, member.username + "'s account still active")

    return render(request, 'accounts/user_view.html', {'member':member})

@user_passes_test(lambda u: u.is_superuser)
def activate(request, user_id):
    member = User.objects.get(id=user_id)
    try:
        member.is_active=True
        member.save()
        messages.success(request, member.username + "'s account reactivated")
    except:
        messages.warning(request, member.username + "'s account was not activated")

    return render(request, 'accounts/user_view.html', {'member':member})

@user_passes_test(lambda u: u.is_superuser)
def makeSiteManager(request, user_id):
    member = User.objects.get(id=user_id)
    try:
        member.is_superuser=True
        member.save()
        messages.success(request, member.username + " made into a site manager")
    except:
        messages.warning(request, member.username + " not made into a site manager")

    return render(request, 'accounts/user_view.html', {'member':member})

@user_passes_test(lambda u: u.is_superuser)
def unmakeSiteManager(request, user_id):
    member = User.objects.get(id=user_id)
    try:
        member.is_superuser=False
        member.save()
        messages.success(request, member.username + " is no longer a site manager")
    except:
        messages.warning(request, member.username + " is still a site manager")

    return render(request, 'accounts/user_view.html', {'member':member})

@user_passes_test(lambda u: u.is_superuser)
def groupsSM(request):
    if request.method == 'POST':
        if request.POST.get('user_name'):
            user_name = request.POST.get('user_name')
            group_name = request.POST.get('group_name')
            try:
                user = User.objects.get(username=user_name)
                group = Group.objects.get(name=group_name)
                user.groups.add(group)
                user.save()

accounts/templates/accounts/groups.html
{% extends "master/base.html" %}
{% block body_block %}

    <h1>Groups</h1>
    <br/>
    <div class="panel panel-default">
        <div class="panel-heading">My Groups</div>
        <table class="table">
            {% for group in user.groups.all %}
                <tr>
                    <th class="list-group-item">{{ group.name }}</th>
                    <td>
                    Members:
                    <ul>
                        {% for member in group.user_set.all %}
                            <li>{{ member.username }}</li>
                        {% endfor %}
                    </ul>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <br/>
    <h3>Create new group</h3>
    <form class="form-inline" method="post" action="/accounts/groups/">
        <div class="form-group">
            {% csrf_token %}
            <input type="text" name="group_name" class="form-control" placeholder="New Group Name">
        </div>
        <button type="submit" class="btn btn-default">Create New Group</button>
    </form>


    <h3>Add other members to a group</h3>
    <form class="form-inline" method="post" action="/accounts/groups/">
        <div class="form-group">
            {% csrf_token %}
            <select name="group_name" class="form-control">
                {% for group in user.groups.all %}
                    <option value="{{ group.name }}">{{ group.name }}</option>
                {% endfor %}
            </select>
            <input type="text" name="user_name" class="form-control" placeholder="Username to add">
        </div>
        <button type="submit" class="btn btn-default">Add User to Group</button>
    </form>
{% endblock %}

accounts/templates/accounts/login.html
{% extends "master/base.html" %}
{% block body_block %}
        <h1>Login</h1>

        <form id="login_form" method="post" action="/accounts/login/">
            {% csrf_token %}
            <label for="username">Username</label>
            <input class="form-control" type="text" name="username" value="" size="50" />
            <br />
            <label for="password">Password</label>
            <input class="form-control" type="password" name="password" value="" size="50" />
            <br />

            <input type="submit" value="submit" class="btn btn-default" />
        </form>
{% endblock %}

accounts/templates/accounts/register.html
{% extends "master/base.html" %}
{% block body_block %}
        <h1>Register</h1>

        {% if registered %}
        <H2>You are Registered. <a href="{% url 'master:index' %}">Continue to Home Page.</a></H2>
        {% else %}

        <form id="user_form" method="post" action="/accounts/register/" enctype="multipart/form-data">

            {% csrf_token %}

            <!-- Display each form. The as_p method wraps each element in a paragraph
                 (<p>) element. This ensures each element appears on a new line,
                 making everything look neater. -->
            {% for field in user_form.visible_fields %}
            <div class="form-group">
            {{ field.errors }}
            <label>{{ field.label }}</label>
            {{ field }}
            </div>
            {% endfor %}

            <!-- Provide a button to click to submit the form. -->
            <input class="btn btn-primary" type="submit" name="submit" value="Register" />
        </form>
        {% endif %}
{% endblock %}

accounts/templates/accounts/sitemanager.html
{% extends "master/base.html" %}
{% block body_block %}
    <h1>Manage Site</h1>
    <div class="panel panel-default">
        <div class="panel-heading">
            List of Users
        </div>
        <table class="table">
            <tr>
                <th>Name</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Email</th>
                <th>Active?</th>
                <th>Site Manager?</th>
            </tr>
            {% for member in all_users %}
                {% if member.username != user.username %}
                    <tr>
                        <td><a href="{% url 'accounts:user_view' member.id %}">{{ member.username }}</a></td>
                        <td> {{ member.first_name }} </td>
                        <td> {{ member.last_name }} </td>
                        <td> {{ member.email }} </td>
                        <td> {{ member.is_active }} </td>
                        <td> {{ member.is_superuser }} </td>
                    </tr>
                {% endif %}
            {% endfor %}
        </table>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            List of Groups
        </div>
        <table class="table">
            {% for group in all_groups %}
                <tr><td>{{ group.name }}</td></tr>
            {% endfor %}
        </table>
    </div>

    <h4>Add user to a group</h4>
    <form class="form-inline" method="post" action="/accounts/groups/sitemanager/">
        <div class="form-group">
            {% csrf_token %}
            <select name="group_name" class="form-control">
                {% for group in all_groups %}
                    <option value="{{ group.name }}">{{ group.name }}</option>
                {% endfor %}
            </select>
            <input type="text" name="user_name" class="form-control" placeholder="Username to add">
        </div>
        <button type="submit" class="btn btn-default">Add User to Group</button>
    </form>

    <h4>Create new group</h4>
    <form class="form-inline" method="post" action="/accounts/groups/sitemanager/">
        <div class="form-group">
            {% csrf_token %}
            <input type="text" name="group_name" class="form-control" placeholder="New Group Name">
        </div>
        <button type="submit" class="btn btn-default">Create New Group</button>
    </form>
{% endblock %}

accounts/templates/accounts/user_view.html
{% extends "master/base.html" %}
{% block body_block %}

    <h1>{{ member.first_name }} {{ member.last_name }}</h1>


    <h3>Reports and Folders</h3>

    {% for folder in member.folder_set.all %}
        <div class="panel panel-default">
            <div class="panel-heading">
                {{ folder.label }}
            </div>
            <table class="table">
                <tr>
                    <th>Name</th>
                    <th>Public</th>
                    <th>Date Created</th>
                    <th>Actions</th>
                </tr>
                {% for report in folder.reports.all %}
                    <tr>
                        <td><a href="{% url 'reports:read_report' report.id %}">{{ report.title }}</a></td>
                        <td>{{ report.public }}</td>
                        <td>{{ report.create_date }}</td>
                        <td><a href="{% url "reports:delete_report" report.id %}">Delete</a></td>

                    </tr>
                {% endfor %}
            </table>
        </div>
    {% endfor %}
    <h3>Groups</h3>
    <div class="panel panel-default">
        <table class="table">
            {% for group in member.groups.all %}
                <tr>
                    <td>{{ group.name }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>




    <h3>Options</h3>
    <div class="row">
        <div class="col-md-6">
            <div class="well">
                {% if member.is_active %}
                    <a class="btn btn-default" href="{% url 'accounts:deactivate' member.id %}">Deactivate User
                        Account</a>
                {% endif %}
                {% if not member.is_active %}
                    <a class="btn btn-default" href="{% url 'accounts:activate' member.id %}">Activate User Account</a>
                {% endif %}
            </div>
        </div>
        <div class="col-md-6">
            <div class="well">
                {% if member.is_superuser %}
                    <a class="btn btn-default" href="{% url 'accounts:unmakeSiteManager' member.id %}">Unmake Site
                        Manager</a>
                {% endif %}
                {% if not member.is_superuser %}
                    <a class="btn btn-default" href="{% url 'accounts:makeSiteManager' member.id %}">Make Site
                        Manager</a>
                {% endif %}


            </div>
        </div>
    </div>

{% endblock %}