SecureShare/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from master import views as master

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
    url(r'^reports/', include('reports.urls', namespace="reports")),
    url(r'^$', include('master.urls', namespace="master")),
    url(r'^messages/', include('post.urls', namespace="messages")),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^tinymce/', include('tinymce.urls')),
]

post/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^new/$', views.new, name='new'),
    url(r'^inbox/$', views.inbox, name='inbox'),
    url(r'^(?P<message_id>[0-9]+)/delete/$', views.delete, name='delete'),
    url(r'^(?P<message_id>[0-9]+)/read/$', views.read, name='read'),
]

post/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Message(models.Model):
    sender = models.ForeignKey(User, related_name="sender")
    recipient = models.ForeignKey(User, related_name="recipient")
    unread = models.BooleanField(default=True)
    encrypted = models.BooleanField(default=False)
    subject = models.CharField(max_length=30)
    content = models.BinaryField()
    key = models.CharField(max_length=80)
    send_date = models.DateField()

post/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Message
from tinymce.widgets import TinyMCE


class MessageForm(forms.Form):
    recipient = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    subject = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    content = forms.CharField(widget=TinyMCE(attrs={'cols': 80, 'rows': 30}))
    encrypted = forms.BooleanField(required=False)
    #class Meta:
     #   model = Message
      #  fields = ('recipient', 'subject', 'content', 'encrypted',)

class KeyForm(forms.Form):
    pem_file = forms.FileField()

post/views.py
import os
from Crypto.PublicKey import RSA
from Crypto import Random
from django.utils import timezone
from django.shortcuts import render
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import messages
from .forms import MessageForm, KeyForm
from django.contrib.auth.models import User
from .models import Message
from django.core.mail import send_mail
# Create your views here.

@login_required
def inbox(request):
    return render(request, 'messages/inbox.html', {'key_form': KeyForm()})

@login_required
def delete(request, message_id):
    try:
        Message.objects.get(id=message_id).delete()
        messages.success(request, 'Message Deleted.')
    except:
        messages.warning(request, 'Message Failed to Delete.')
    return HttpResponseRedirect('/messages/inbox')

@login_required
def read(request, message_id):
    message = Message.objects.get(id=message_id)
    message.unread = False
    message.save()
    if request.method == 'POST':
        f = KeyForm(request.POST, request.FILES)
        if f.is_valid():
            #try:
            key = RSA.importKey(f.cleaned_data['pem_file'].read(), request.user.security.pem_key)
            content = key.decrypt(message.content.tobytes())
            return render(request, 'messages/read.html', {'message': message, 'content': content})
            #except:
            #    messages.warning(request, 'Decryption did not occur: PEM file invalid')
            #    return HttpResponseRedirect('/messages/inbox')
        else:
            messages.warning(request, 'Decryption did not occur: File upload error.')
            return render(request, 'messages/inbox.html', {'key_form': f})
    if message.recipient.id == request.user.id:
        return render(request, 'messages/read.html', {'message': message, 'content': message.content.tobytes().decode('utf-8')})
    else:
        return HttpResponseRedirect('/messages/inbox')


@login_required
def new(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        f = MessageForm(request.POST)
        # check whether it's valid:
        if f.is_valid():
            # Save the form data to the database.
            # But dont yet commit, we still have some data to add.
            message = Message()
            message.sender = request.user
            message.subject = f.cleaned_data['subject']
            message.content = f.cleaned_data['content'].encode()
            try:
                message.recipient = User.objects.get(username=f.cleaned_data['recipient'])
            except:
                messages.warning(request, 'Message not sent: Recipient username not found!')
                return render(request, 'messages/new.html', {'message_form': f})
            if f.cleaned_data['encrypted']:
                message.encrypted = True
                key = RSA.importKey(message.recipient.security.public_key, "password")
                message.content = key.publickey().encrypt(message.content, 32)[0]

            message.send_date = timezone.now()
            # NOW we can save
            message.save();

            # redirect to a new URL:
            messages.success(request, 'Message Sent')
            return HttpResponseRedirect('/messages/inbox')
        else:
            messages.warning(request, 'Message Failed to Send!')
            return render(request, '/messages/new.html', {'message_form': f})
    # if a GET (or any other method) we'll create a blank form
    else:
        message_form = MessageForm()
        return render(request, 'messages/new.html', {'message_form': message_form})

    return render(request, 'messages/new.html')

post/templates/messages/inbox.html
{% extends "master/base.html" %}
{% block body_block %}
<div class="well">
  <a class="btn btn-default" href="{% url 'messages:new' %}">New Message</a>
</div>


<div class="panel panel-default">
  <div class="panel-heading">
      Inbox
  </div>
    <table class="table">
      <tr>
        <th>Subject</th>
        <th>Sent By</th>
        <th>Date Sent</th>
        <th>Encrypted</th>
        <th>Actions</th>
      </tr>
      {% for message in user.recipient.all %}

      <tr>
        <td>
          {% if message.encrypted %} <a data-toggle="modal" data-target="#form{{ message.id }}">{{ message.subject}}</a>
          {% else %}<a href="{% url 'messages:read' message.id %}">{{ message.subject}}</a>{% endif %}
          {% if message.unread %}<span class="label label-info">UNREAD</span>{% endif %}
        </td>
        <td>{{ message.sender }}</td>
        <td>{{ message.send_date }}</td>
        <td>{{ message.encrypted }}</td>
        <td> <a href="{% url 'messages:delete' message.id %}">Delete</a></td>
      </tr>
      {% endfor %}
    </table>
</div>

{% for message in user.recipient.all %}
{% if message.encrypted %}
<div class="modal fade" id="form{{ message.id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">"{{ message.subject }}" is an encrypted message</h4>
      </div>
      <form method="post" enctype="multipart/form-data" action="/messages/{{ message.id }}/read/">
      <div class="modal-body">
      {% csrf_token %}
        <p>Please upload your encrypted PEM file. It was emailed to you when you created your account. All information is transferred over SSL.</p>
        {% for field in key_form.visible_fields %}
        <div class="form-group">
          {{ field.errors }}
          <label>{{ field.label }}</label>
          {{ field }}
        </div>
        {% endfor %}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">View Message</button>
      </div>
    </form>
    </div>
  </div>
</div>
{% endif %}
{% endfor %}

{% endblock %}

post/templates/messages/new.html
{% extends "master/base.html" %}
{% block head_block %}
    <head>
        <script src="//tinymce.cachefly.net/4.1/tinymce.min.js"></script>
        <script>
            tinymce.init({
                selector: 'textarea',
                height: 500,
                plugins: [
                    'advlist autolink lists link image charmap print preview anchor',
                    'searchreplace visualblocks code fullscreen',
                    'insertdatetime media table contextmenu paste code'
                ],
                toolbar: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
                content_css: [
                    '//fast.fonts.net/cssapi/e6dc9b99-64fe-4292-ad98-6974f93cd2a2.css',
                    '//www.tinymce.com/css/codepen.min.css'
                ]

            });</script>

        {{ message_form.media }}
    </head>
{% endblock %}

{% block body_block %}
    <body>
    <h3>New Message</h3>

    <form method="post" action="/messages/new/">
        {% csrf_token %}
        {% for field in message_form.visible_fields %}
            <div class="form-group">
            {{ field.errors }}
            <label>{{ field.label }}</label>
            {{ field }}

            <div>
        {% endfor %}
        <br/>
        <button type="submit" class="btn btn-default">Send</button>
    </form>
    </body>

{% endblock %}

post/templates/messages/read.html
{% extends "master/base.html" %}
{% block body_block %}
<div class="well">
  <a class="btn btn-default" href="{% url 'messages:inbox' %}">Back to Inbox</a>
  <a class="btn btn-default" href="{% url 'messages:new' %}">New Message</a>
  <a class="btn btn-danger" href="{% url 'messages:delete' message.id %}">Delete Message</a>
</div>

<div class="page-header">
  <h1>{{ message.subject }}  <small>Sent by {{ message.sender.username }}</small></h1>
</div>
{% if message.encrypted %}
<div class="panel panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title">This message is encrypted!</h3>
  </div>
</div>
{% endif %}
{{ content|safe }}

{% endblock %}