SecureShare/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from master import views as master

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
    url(r'^reports/', include('reports.urls', namespace="reports")),
    url(r'^$', include('master.urls', namespace="master")),
    url(r'^messages/', include('post.urls', namespace="messages")),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^tinymce/', include('tinymce.urls')),
]

accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^groups/$', views.groups, name='groups'),
    url(r'^sitemanager/$', views.sitemanager, name='sitemanager'),
    url(r'^(?P<user_id>[0-9]+)/user_view/$', views.user_view, name='user_view'),
    url(r'^(?P<user_id>[0-9]+)/deactivate/$', views.deactivate, name='deactivate'),
    url(r'^(?P<user_id>[0-9]+)/activate/$', views.activate, name='activate'),
    url(r'^(?P<user_id>[0-9]+)/makeSiteManager/$', views.makeSiteManager, name='makeSiteManager'),
    url(r'^(?P<user_id>[0-9]+)/unmakeSiteManager/$', views.unmakeSiteManager, name='unmakeSiteManager'),
    url(r'^groups/sitemanager/$', views.groupsSM, name='groupsSM'),
]

master/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),

]

post/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^new/$', views.new, name='new'),
    url(r'^inbox/$', views.inbox, name='inbox'),
    url(r'^(?P<message_id>[0-9]+)/delete/$', views.delete, name='delete'),
    url(r'^(?P<message_id>[0-9]+)/read/$', views.read, name='read'),
]

reports/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^reports/$', views.reports, name='reports'),
    url(r'^folders/$', views.folders, name='folders'),
    url(r'^search_reports/$', views.search, name = 'search'),
    url(r'^attachments/$', views.attachments, name='attachments'),
    url(r'^(?P<report_id>[0-9]+)/contributors/$', views.contributors, name='contributors'),
    url(r'^public/$', views.public, name='public'),
    url(r'^(?P<report_id>[0-9]+)/edit_report/$', views.edit_report, name='edit_report'),
    url(r'^(?P<report_id>[0-9]+)/delete_report/$', views.delete_report, name='delete_report'),
    url(r'^(?P<folder_id>[0-9]+)/edit_folder/$', views.edit_folder, name='edit_folder'),
    url(r'^move/$', views.move, name='move'),
    url(r'^(?P<report_id>[0-9]+)/attachments/$', views.attachments, name='attachments'),
    url(r'^(?P<report_id>[0-9]+)/read_report/$', views.read_report, name='read_report'),
    url(r'^(?P<attachment_id>[0-9]+)/delete_attachment/$', views.delete_attachment, name='delete_attachment'),
    url(r'^api_available_reports/$', views.api_available_reports, name='api_available_reports'),
    url(r'^api_public_reports/$', views.api_public_reports, name='api_public_reports'),
    url(r'^(?P<attachment_id>[0-9]+)/download_attachment/$', views.api_download_attachment, name='api_download_attachment'),
    url(r'^api_add_report/$', views.api_add_report, name='api_add_report'),

]

master/models.py
from django.db import models

# Create your models here.

master/views.py
from django.shortcuts import render
from reports.models import Report, Folder

# Create your views here.

def index(request):
    return render(request, 'master/index.html', {})

master/templates/master/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SecureShare | {% block title %}This page{% endblock %}</title>

    <link href="https://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  {% block head_block %}{% endblock %}
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">SecureShare</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
                <li><a href="/">Home</a></li>
                <li><a href="{% url 'reports:public' %}">Public Reports</a></li>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                    {% endif %}
              </ul>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          {% if not user.is_authenticated %}
          <form id="login_form" method="post" action="/accounts/login/">
            {% csrf_token %}
            <label for="username">Username</label>
            <input class="form-control" type="text" name="username" value="" size="50" />
            <br />
            <label for="password">Password</label>
            <input class="form-control" type="password" name="password" value="" size="50" />
            <br />
            <input type="submit" value="Login" class="btn btn-default btn-block" />
          </form>
          {% else %}
          <a class="btn btn-primary btn-block" href="{% url 'accounts:logout' %}">Logout</a>
          <a class="btn btn-default btn-block" href="{% url 'accounts:groups' %}">Manage Groups</a>
          <a class="btn btn-default btn-block" href="{% url 'messages:inbox' %}">Messages <span class="badge">{{user.get_unread}}</span></a>
            {% if user.is_superuser %}
                <a class="btn btn-default btn-block" href="{% url 'accounts:sitemanager' %}">Site Manager</a>
            {% endif %}

          {% endif %}
          {% block side_block %}{% endblock %}
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
           <div>
             {% if messages %}
             <div class="messages">
               {% for message in messages %}
               <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %}">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
               </div>
               {% endfor %}
             </div>
             {% endif %}
             {% block body_block %}{% endblock %}
           </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="https://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

master/templates/master/index.html
{% extends "master/base.html" %}
{% block body_block %}
{% if user.is_authenticated %}
<h2>Hello {{ user.first_name }}. Welcome to SecureShare!</h2>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script type="text/javascript">
    document.write("\<script src='http://code.jquery.com/jquery-latest.min.js' type='text/javascript'>\<\/script>");
</script>

    <div class="row">
        <div class="col-md-6">
            <div class="well">
                <a class="btn btn-default" href="{% url 'reports:reports' %}">New Report</a>
            </div>
        </div>
        <div class="col-md-6">
            <div class="well">
                <form class="form-inline" method="post" action="/reports/folders/">
                    <div class="form-group">
                        {% csrf_token %}
                        <input type="text" name="folder_name" class="form-control" size ="36" placeholder="New Folder Name">
                    </div>
                    <button type="submit" class="btn btn-default">Create New Folder</button>
                </form>
            </div>
        </div>
        <div class="col-md-12">
                <div class="well">
                    <form class="form-inline" method="get" action="/reports/search_reports">
                        <input type="text" class="form-control" size="90" name="q" id="id_q" placeholder="Enter Search Keywords"/>
                        <input type="submit" class="btn btn-default" value="Search"/>
                    </form>
                </div>
        </div>
    </div>

<script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        $("input[type='button']").click(function(){
        	var radioValue = $("input[name='search']:checked").val();
            if(radioValue){
                alert("You are a - " + radioValue);
            }
        });

    });
</script>


{% for folder in user.folder_set.all %}
<div class="panel panel-default">
  <div class="panel-heading">
      {{ folder.label }}
      {% if folder.label != "Uncategorized"%}
        {% if folder.label != "Shared With Me"%}
            <a class="btn btn-default pull-right btn-sm" href="{% url "reports:edit_folder" folder.id %}">Edit Folder</a>
            <div class="clearfix"></div>
        {% endif %}
      {% endif %}
  </div>
    <table class="table">
      <tr>
        <th>Name</th>
          <th>Creator</th>
        <th>Public</th>
        <th>Date Created</th>
          <th>Attachments</th>
        <th>Actions</th>
        <th>Move to...</th>
      </tr>
      {% for report in folder.reports.all %}
      <tr>
        <td><a href="{% url 'reports:read_report' report.id %}">{{ report.title }}</a></td>
        <td> {{ report.creator }} </td>
        <td>{{ report.public }}</td>
        <td>{{ report.create_date }}</td>
      <td>
        <button type="button" class="btn btn-link" data-toggle="collapse" data-target="#attach{{report.id}}">Click for all Attachments</button>
        <div id="attach{{report.id}}" class="collapse">
            <ul>
            {% for attachment in report.attachment_set.all %}<li>{{ attachment.name }}</li>{% endfor %}

            </ul>
            </div>
      </td>
        <td> <a href="{% url "reports:edit_report" report.id %}">Edit</a> &nbsp; &nbsp;
          <a href="{% url "reports:delete_report" report.id %}">Delete</a></td>
        <td>
          <form id="move{{report.id}}" method="post" action="/reports/move/">
          {% csrf_token %}
            <select name="move_to" onChange = "$('#move{{report.id}}').submit()">
              <option value="" disabled="disabled" selected="selected">Please select a folder</option>
                {% for listfold in user.folder_set.all %}
                {% if listfold.label != folder.label %}
                    {% if listfold.label != "Shared With Me" %}
                    <option value="{{listfold.id}}">{{ listfold.label }}</option>
              {% endif %}
                {% endif %}
              {% endfor %}
                <input type="hidden" name="move_from" value="{{folder.id }}">
            <input type="hidden" name="currep" value="{{report.id}}">
            </select>
            </form>
        </td>
      </tr>
      {% endfor %}
    </table>
</div>
{% endfor %}


{% else %}
<div class="jumbotron">
  <h1>Welcome to SecureShare</h1>
  <p>An Information System to Support Secure Information Sharing</p>
  <p><a class="btn btn-primary btn-lg" href="{% url 'accounts:register' %}" role="button">Register Now</a></p>
</div>
<p>Many small groups in the world need a means to collect, share, and distribute information securely, without risking it falling into the wrong hands on their own computer or servers, and without it being lost due to other reasons (theft, viruses, etc). Examples of such groups include grassroots organizations, new businesses, political groups, freedom fighters, human rights organizations, journalists, etc.</p>
{% endif %}
{% endblock %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script language="JavaScript" type="text/javascript" src="/js/jquery-1.2.6.min.js"></script>
<script language="JavaScript" type="text/javascript" src="/js/jquery-ui-personalized-1.5.2.packed.js"></script>
<script language="JavaScript" type="text/javascript" src="/js/sprinkle.js"></script>
<script type="text/javascript">
    document.write("\<script src='http://code.jquery.com/jquery-latest.min.js' type='text/javascript'>\<\/script>");
</script>